[package]
name = "tabiew"
version = "0.6.2"
authors = ["Shayan Hashemi <shshemi@gmail.com>"]
license = "MIT"
edition = "2021"
description = "Tabiew is a lightweight, terminal-based application to view and query delimiter separated value formatted documents, such as CSV and TSV files."
repository = "https://github.com/shshemi/tabiew"
documentation = "https://docs.rs/tabiew"
homepage = "https://github.com/shshemi/tabiew"

[[bin]]
name="tw"
path="src/main.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
crossterm = "0.28.1"
itertools = "0.13.0"
polars = { version = "0.42.0", features = ["dtype-decimal", "lazy", "polars-sql", "polars-io", "parquet"] }
polars-sql = "0.42.0"
rand = "0.8.5"
ratatui = "0.28.0"
tempfile = "3.12.0"

[build-dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap_mangen = { version = "0.2.23"}
clap_complete = { version = "4.5.19"}

[package.metadata.deb]
license-file = [ "LICENSE", "4" ]
depends = "$auto"
extended-description = """
Tabiew is a lightweight, terminal-based application to view and query delimiter separated value formatted documents, such as CSV and TSV files.
"""
section = "utils"
priority = "optional"
assets = [
    [ "target/release/tw", "/usr/bin/tw", "0755" ],
    [ "target/manual/tabiew.1", "/usr/share/man/man1/tw.1", "0644" ],
    [ "target/manual/tabiew.1", "/usr/share/man/man1/tabiew.1", "0644" ],
    [ "target/completion/tw.bash", "/usr/share/bash-completion/completions/tw.bash", "0644" ],
    [ "target/completion/_tw", "/usr/share/zsh/vendor-completions/_tw", "0644" ],
    [ "target/completion/tw.fish", "/usr/share/fish/completions/tw.fish", "0644" ],
]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/tw", dest = "/usr/bin/tw", mode = "755" },
    { source = "target/manual/tabiew.1", dest = "/usr/share/man/man1/tw.1", mode = "0644" },
    { source = "target/manual/tabiew.1", dest = "/usr/share/man/man1/tabiew.1", mode = "0644" },
    { source = "target/completion/tw.bash", dest = "/usr/share/bash-completion/completions/tw.bash", mode = "0644" },
    { source = "target/completion/_tw", dest = "/usr/share/zsh/vendor-completions/_tw", mode = "0644" },
    { source = "target/completion/tw.fish", dest = "/usr/share/fish/completions/tw.fish", mode = "0644" },
]

[profile.release]
lto = true
strip = true
opt-level = 3
codegen-units = 1
panic = 'abort'

